ARDUINO_DIR = /usr/share/arduino
ARDUINO_PORT = /dev/ttyACM0

USER_LIB_PATH = /home/pls/ydlidar_ws/src/ydlidar_ros/src/arduino/runTestModule/runTestModule
BOARD_TAG = mega2560

include /usr/share/arduino/Arduino.mk
